services:
  app:
    build:
      context: ..
      dockerfile: ./hw_2/Dockerfile
    ports:
      - '8000:8000'

#  prometheus:
#    image: prom/prometheus
#    container_name: prometheus
#    command:
#      - '--config.file=/etc/prometheus/config.yml'
#    ports:
#      - '9090:9090'
#    restart: unless-stopped
#    volumes:
#      - ./prometheus:/etc/prometheus
#      - prom_data:/prometheus
#
#  grafana:
#    image: grafana/grafana
#    container_name: grafana
#    ports:
#      - '3000:3000'
#    restart: unless-stopped
#    environment:
#      - GF_SECURITY_ADMIN_USER=admin
#      - GF_SECURITY_ADMIN_PASSWORD=grafana
#    volumes:
#      - ./grafana/provisioning:/etc/grafana/provisioning
#      - ./grafana/dashboards:/var/lib/grafana/dashboards
#
#volumes:
#  prom_data: