services:
  app:
    image: app
    build:
      context: ..
      dockerfile: ./hw_2/Dockerfile
    ports:
      - '8000:8000'
    restart: always
    networks:
      - mynetwork

  prometheus:
    image: prom/prometheus:v2.30.3
    ports:
      - 9090:9090
    networks:
      - mynetwork
    depends_on:
      - app
    restart: always
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yaml

  grafana:  # login: admin, password: admin
    image: grafana/grafana:latest
    ports:
      - 3333:3000
    networks:
      - mynetwork
    depends_on:
      - app
      - prometheus
    restart: always
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana-data:/var/lib/grafana

networks:
  mynetwork: {}

volumes:
  prometheus-data: {}
  grafana-data: {}